language: java

before_install:
  - sudo apt-get update
  - sudo apt-get -y install texlive-latex-base
  - sudo apt-get -y install texlive-fonts-recommended
  - sudo apt-get -y install texlive-latex-extra
  - sudo apt-get -y install cm-super

script:
  - mvn install -Dmaven.javadoc.skip=true -B -V